version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "rvkernel-manager"
    schedule:
      interval: "daily"
    groups:
      maven:
        patterns:
          - "*"
