[versions]
agp = "8.0.0"
kotlin = "2.1.0"
activity = "1.5.1"
bom = "2024.11.00"
material3 = "1.3.1"
ui = "1.7.5"
core = "1.15.0"
lifecycle = "2.8.7"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "bom" }

androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
