name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup NDK r28
      run: sdkmanager "ndk;28.1.13356709"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug
      run: ./gradlew assembleDebug

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: RvKernel-Manager-Debug
        path: |
          app/build/outputs/apk/debug/app-debug.apk
